### ISSUE TITLE
Will need to `s/kosgrz/mattermost/` once the repo is transferred

### ISSUE THREAD

**Issue by jfrerich** [mattermost-community/mattermost-plugin-bitbucket#21]
Replace occurrences of the authors repo and substitute for `mattermost`

_Originally posted by @jfrerich in https://github.com/mattermost/mattermost-plugin-bitbucket/pull/5#discussion_r556004626_

**Comment by hanzei** [comment]
@jfrerich Can we close this?

**Comment by jfrerich** [comment]
Yes! Closing
