### ISSUE TITLE
Add slash command autocomplete functionality to Bitbucket 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost-community/mattermost-plugin-bitbucket#51]
Bitbucket does not have any auto-complete functionality for the available subcommands.

Given how many subcommands are available this would be very useful. 

Steps:
- Type `/bitbucket` and a space. 

**Observed**No subcommands are shown.

**Comment by DHaussermann** [comment]
@aaronrothschild Autocomplete has somewhat become the standard for any plugin we've released for a while. 0/5 If this is low risk and mana we should even consider adding it for the upcoming `v1.1.1` release.

**Comment by aaronrothschild** [comment]
I'm worried about pushing this out further.  if this can be done within the release timeframe (before eend of November) I'm OK with us taking it on.  I've placed it in v 1.2 milestone, but it can be moved to 1.1
