### ISSUE TITLE
Poor UX when trying to create an issue if the repository does not permit it

### ISSUE THREAD

**Issue by DHaussermann** [mattermost-community/mattermost-plugin-bitbucket#55]
If a repo in bitbucket has issue creation disabled, the plugin UX does not handle this gracefully.
We show an error message in the modal that should instead show a non-technical message to explain issue creation is not allowed keeping only the text from the message.
![image](https://user-images.githubusercontent.com/35588783/147148321-169d1202-7b01-46a8-afcc-f15bb7fa2037.png)

Steps:
- Login to your Bitbucket org such as https://bitbucket.org/DHaussermann
- Setup and configure the plugin oAuth using the instructions in the read-me
- Connect a test user
- Select any repo in the organization and disable issue creation
- Make or locate a post
- Select the ... menu and _Create Bitbucket Issue_
- Select the repository from the dropdown where issue creation has been disabled 
- Click Submit

**Observed**: `{"id":"","message":"failed to create issue: Sorry, either you don't have access to the repo DHaussermann/helloworld with the user dkh-sysadmin or it is no longer available","status_code":404}`

**Comment by hanzei** [comment]
Same issue as https://github.com/mattermost/mattermost-plugin-github/issues/318. We can copy the solution from https://github.com/mattermost/mattermost-plugin-github/pull/333.
