### ISSUE TITLE
Bitbucket does not show a fallback image when the connected user has no profile image set 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost-community/mattermost-plugin-bitbucket#59]
When the connected user has no profile image set, Bitbucket app does not provide a fallback generic image for the plugin to use. The user then see's a "broken image" which seems to be added by the browser. 

![image](https://user-images.githubusercontent.com/35588783/147152684-262bd621-e757-48b7-a1ed-c6dc12206232.png)

On the Bitbbucket side, this case is handled by showing an image of initials such as `DH` but this generic profile image does not seem to make it back to Mttermost 
**note**0/5 if there is a way we can fix this from the plugin side.   

So far as I can tell, this may only show in cases where the affected user uses the `/bitbucket me` command

Steps:
- Setup bitbucket
- On the Bitbucket side, create or locate a user who does not have a profile image and only initials are shown
- In Mattermost connect as this Bitbucket user
- Type `/bitbucket me`

**Observed** Broken image is shown.

**Comment by hanzei** [comment]
@hanzei to investigate if this can be fixed with MD. Otherwise remove the profile icon entirely.

**Comment by hanzei** [comment]
The image should be removed.

**Comment by dipak-demansol** [comment]
@DHaussermann issue is not Regenerated, Tested with master, can you Confirm again that issue is still regenerated? 
Tested in 
Mattermost Version: 6.0.0-rc3
Database Schema Version: 6.0.0
