### ISSUE TITLE
Subscription to Repo with pushes - doesnt trigger

### ISSUE THREAD

**Issue by NatsuDragneelKl** [mattermost-community/mattermost-plugin-bitbucket#84]
Bitbucket is connected, and the Channel is successfull subscribed with pushes.

Bitbucket webhook is created but return error 400 (no message)

Is this a known issue?

**Comment by NatsuDragneelKl** [comment]
Ok, reconfiguration of Bitbucket and Mattermost stuff as described in Docu removes 400 error.

Webhook now have 200 but no message in channel where i have subscribed to this repo with feature "pushes"

**Comment by catalintomai** [comment]
@Flinch , can you take a look and see if you can get a consistent repro. Thanks.
